changelog:
  categories:
    - title: 💥 Breaking changes
      labels:
        - breaking
    - title: 🚨 Removed
      labels:
        - removed
    - title: ⚠️ Deprecated
      labels:
        - deprecated
    - title: 🚀 New features and improvements
      labels:
        - enhancement
        - feature
        - feat
        - rfe
    - title: 🐛 Bug fixes
      labels:
        - bug
        - fix
        - bugfix
        - regression
        - regression-fix
    - title: 📝 Documentation updates
      labels:
        - documentation
        - doc
        - docs
    - title: 👻 Maintenance
      labels:
        - chore
        - internal
        - maintenance
    - title: 🚦 Tests
      labels:
        - test
        - tests
